version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      PORT: 80
      DB_HOST: jobplex1.cixko6g8cczy.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: philgabby2003
      DB_NAME: jobplex
      DB_SSL: "false"  # Add this to explicitly disable SSL requirement
      JWT_SECRET: your_secret_key_here
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/package.json:/usr/src/app/package.json
      - ./backend/tsconfig.json:/usr/src/app/tsconfig.json
      - /usrsrc/app/node_modules
    restart: unless-stopped

  # PgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobplex.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped