name: Frontend Selective Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Only trigger when frontend files change
  pull_request:
    types:
      - opened
    paths:
      - 'frontend/**' # Only trigger for PRs affecting frontend
  workflow_dispatch: # Manual trigger option remains unchanged

env:
  MyPAss: 1234

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for path filtering
      
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
  
  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend-changed == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('frontend/package-lock.json')}}
      
      - name: Install dependencies
        run: |
          cd frontend 
          npm install
      
      - name: Build Code
        run: |
          cd frontend 
          npm run build
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Get Build files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      
      - name: Output Contents
        run: |
          echo "Root directory:"
          ls -la
          echo "Dist directory:"
          ls -la ./dist
      
      - name: Deploy
        id: deploy
        uses: ./.github/actions
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
        with:
          bucket: jobplex-frontend
          dist-folder: ./dist/jobplex/browser
          bucket-region: us-east-1
      
      - name: Output URL
        run: echo "Live URL:${{steps.deploy.outputs.website-url}}"